import os

MAX_TRANSCRIPT_WORD_COUNT = 3000
MAX_TOTAL_SCRAPE_WORD_COUNT = 3000
MAX_IMAGES_TO_INCLUDE = 10
MAX_LINKS_TO_TAKE = 6
MIN_LINKS_TO_TAKE = 3
AUDIO_TRANSCRIBE_SIZE = "small"
BASE_CACHE_DIR = "./data/audio_cache"

isHeadless = True
POLLINATIONS_ENDPOINT = "https://gen.pollinations.ai/v1/chat/completions"
POLLINATIONS_ENDPOINT_IMAGE = "https://gen.pollinations.ai/image/"

MAX_SESSIONS = 1000
SESSION_TTL_MINUTES = 30
RAG_CONTEXT_REFRESH = True
MODEL_POOL_SIZE = 1
MODEL_MAX_TABS = 20
SEARCH_AGENT_POOL_SIZE = 1
SEARCH_AGENT_MAX_TABS = 20
MODEL_CACHE_CLEANUP_MINUTES = 30
MODEL_CACHE_MAX_AGE_MINUTES = 60

LLM_MODEL = os.getenv("MODEL", "kimi")
IMAGE_MODEL = os.getenv("IMAGE_MODEL", "zimage")
VISION_MODEL = os.getenv("VISION_MODEL", "gemini-fast")
RESPONSE_MODEL = "lixsearch"
LLM_MAX_TOKENS = 3000
LLM_TEMPERATURE = 0.7
LLM_TOP_P = 1.0

SEARCH_MAX_RESULTS = 8
YOUTUBE_MAX_VIDEOS = 2
IMAGE_SEARCH_MAX = 10
FETCH_TIMEOUT = 30
PARALLEL_WORKERS = 10
REQUEST_TIMEOUT = 300

EMBEDDING_BATCH_SIZE = 64
EMBEDDING_DIVERSITY = 0.4

LOG_LEVEL = "INFO"
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
LOG_FILE = None

ENABLE_WEBSOCKET_STREAMING = True
ENABLE_ENTITY_EXTRACTION = True
ENABLE_RELATIONSHIP_DETECTION = True

EMBEDDINGS_DIR = "./data/embeddings"
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
EMBEDDING_DIMENSION = 384
EMEDDING_BATCH_SIZE = 32
EMBEDDING_BATCH_SIZE = 32
CHUNK_SIZE = 600
CHUNK_OVERLAP = 60

SEMANTIC_CACHE_DIR = "./data/cache"
SEMANTIC_CACHE_TTL_SECONDS = 3600
SEMANTIC_CACHE_SIMILARITY_THRESHOLD = 0.90

X_REQ_ID_SLICE_SIZE = 12
RETRIEVAL_TOP_K = 5
SESSION_SUMMARY_THRESHOLD = 6
PERSIST_VECTOR_STORE_INTERVAL = 300
CONVERSATION_CACHE_DIR = "./data/cache/conversation"
CACHE_WINDOW_SIZE = 10
CACHE_COMPRESSION_ENABLED = True
CACHE_SIMILARITY_THRESHOLD = 0.85
CACHE_MAX_ENTRIES = 50
CACHE_TTL_SECONDS = 1800
CACHE_EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
CACHE_MIN_QUERY_LENGTH = 10
CACHE_COMPRESSION_METHOD = "zlib"
REQUEST_ID_LEGACY_SLICE_SIZE = 10
REQUEST_ID_HEX_SLICE_SIZE = 8
LOG_MESSAGE_QUERY_TRUNCATE = 50
LOG_MESSAGE_CONTEXT_TRUNCATE = 100
LOG_MESSAGE_LONG_TRUNCATE = 150
LOG_MESSAGE_PREVIEW_TRUNCATE = 200
LOG_ENTRY_ID_DISPLAY_SIZE = 8
IMAGE_SEARCH_QUERY_WORDS_LIMIT = 15
ERROR_MESSAGE_TRUNCATE = 100
ERROR_CONTEXT_TRUNCATE = 150

LOAD_BALANCER_PORT = 9000
LOAD_BALANCER_HOST = "0.0.0.0"
WORKER_START_PORT = 9002
WORKER_COUNT = 10
WORKER_TIMEOUT = 120
LOAD_BALANCER_HEALTH_CHECK_INTERVAL = 10
LOAD_BALANCER_HEALTH_CHECK_TIMEOUT = 5

CHROMA_API_IMPL = os.getenv("CHROMA_API_IMPL", "http")
CHROMA_SERVER_HOST = os.getenv("CHROMA_SERVER_HOST", "localhost")
CHROMA_SERVER_PORT = int(os.getenv("CHROMA_SERVER_PORT", "8000"))
CHROMA_DB_PATH = "/app/data/embeddings"
CHROMA_BATCH_SIZE = 100
CHROMA_PERSISTENCE_DIR = "/chroma_data"
CHROMA_TELEMETRY_DISABLED = True
CHROMA_LOG_LEVEL = "INFO"

VECTOR_DB_POOL_SIZE = 20
VECTOR_DB_QUERY_TIMEOUT = 30
VECTOR_DB_BATCH_TIMEOUT = 60
VECTOR_DB_CONNECTION_TIMEOUT = 10
VECTOR_DB_MAX_RETRIES = 3
VECTOR_DB_RETRY_DELAY = 2

SEMANTIC_QUERY_CACHE_TTL = 3600
SEMANTIC_QUERY_CACHE_MAX_SIZE = 1000
SEMANTIC_QUERY_CACHE_SIMILARITY_THRESHOLD = 0.98
SEMANTIC_CACHE_CLEANUP_INTERVAL = 300

CONNECTION_POOL_SIZE = 20
CONNECTION_POOL_TIMEOUT = 10.0
CONNECTION_POOL_ENABLE = True

REDIS_ENABLED = True
REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD")
REDIS_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0" if REDIS_PASSWORD else f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
REDIS_SOCKET_CONNECT_TIMEOUT = 5
REDIS_SOCKET_KEEPALIVE = True
REDIS_KEY_PREFIX = "elixpo"

SEMANTIC_CACHE_REDIS_HOST = REDIS_HOST
SEMANTIC_CACHE_REDIS_PORT = REDIS_PORT
SEMANTIC_CACHE_REDIS_DB = 0
SEMANTIC_CACHE_REDIS_TTL_SECONDS = 300
SEMANTIC_CACHE_REDIS_SIMILARITY_THRESHOLD = 0.90
SEMANTIC_CACHE_REDIS_MAX_ITEMS_PER_URL = 50

URL_EMBEDDING_CACHE_REDIS_DB = 1
URL_EMBEDDING_CACHE_TTL_SECONDS = 86400
URL_EMBEDDING_CACHE_BATCH_SIZE = 100

SESSION_CONTEXT_WINDOW_REDIS_DB = 2
SESSION_CONTEXT_WINDOW_TTL_SECONDS = 1800
SESSION_CONTEXT_WINDOW_SIZE = 20
SESSION_CONTEXT_WINDOW_MAX_TOKENS = None

SEMANTIC_CACHE_REDIS_POOL_SIZE = 50
SEMANTIC_CACHE_REDIS_MAX_SESSIONS = 1000
SEMANTIC_CACHE_REDIS_CONNECTION_TIMEOUT = 10
SEMANTIC_CACHE_REDIS_COMPRESSION_ENABLED = False

SEMANTIC_CACHE_REDIS_CLEANUP_INTERVAL = 300
SEMANTIC_CACHE_REDIS_STATS_INTERVAL = 60
SEMANTIC_CACHE_REDIS_ENABLE_MONITORING = True


CONVERSATION_ARCHIVE_DIR = "./data/conversations"
SESSION_DISK_TTL_DAYS = 30                  
SESSION_LRU_EVICT_AFTER_MINUTES = 30        
HYBRID_HOT_WINDOW_SIZE = 20                 
HYBRID_STARTUP_CLEANUP = True               

IPC_HOST = os.getenv("IPC_HOST", "localhost")
IPC_PORT = int(os.getenv("IPC_PORT", "9510"))
_IPC_AUTHKEY = os.getenv("IPC_AUTHKEY", "ipcService")
IPC_AUTHKEY = _IPC_AUTHKEY.encode() if isinstance(_IPC_AUTHKEY, str) else _IPC_AUTHKEY
IPC_TIMEOUT = 30

ENABLE_VECTOR_DB_MONITORING = True
ENABLE_PERFORMANCE_METRICS = True
ENABLE_REQUEST_TRACING = True
METRICS_COLLECTION_INTERVAL = 60
METRICS_RETENTION_DAYS = 7
SLA_CACHE_HIT_LATENCY_MS = 15
SLA_VECTOR_SEARCH_LATENCY_MS = 50
SLA_API_RESPONSE_LATENCY_MS = 2000
DEGRADATION_ENABLE = True
DEGRADATION_TRACK_FAILURES = True
DEGRADATION_FALLBACK_TIMEOUT = 5
DEGRADATION_MIN_ACCEPTABLE_CHANGE = 0.20
