import io
import logging
import re
import uuid
from datetime import datetime
from quart import request, jsonify, Response
from pipeline.config import X_REQ_ID_SLICE_SIZE

logger = logging.getLogger("lixsearch-api")


def _markdown_to_pdf(markdown_text: str, title: str = "lixSearch Response") -> bytes:
    """Convert markdown text to a styled PDF. Handles \\n literals and markdown formatting."""
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(30, 30, 60)
    pdf.cell(0, 12, title, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, f"Generated by lixSearch  |  {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # Normalize literal \n to real newlines
    text = markdown_text.replace("\\n", "\n")

    # Process line by line
    for line in text.split("\n"):
        stripped = line.strip()

        if not stripped:
            pdf.ln(4)
            continue

        # Headers
        if stripped.startswith("### "):
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_text_color(40, 40, 80)
            pdf.multi_cell(0, 7, stripped[4:])
            pdf.ln(2)
        elif stripped.startswith("## "):
            pdf.set_font("Helvetica", "B", 15)
            pdf.set_text_color(30, 30, 60)
            pdf.multi_cell(0, 8, stripped[3:])
            pdf.ln(3)
        elif stripped.startswith("# "):
            pdf.set_font("Helvetica", "B", 17)
            pdf.set_text_color(20, 20, 50)
            pdf.multi_cell(0, 9, stripped[2:])
            pdf.ln(4)
        elif stripped.startswith("- ") or stripped.startswith("* "):
            pdf.set_font("Helvetica", "", 11)
            pdf.set_text_color(50, 50, 50)
            pdf.cell(6)
            pdf.multi_cell(0, 6, f"\u2022  {stripped[2:]}")
            pdf.ln(1)
        elif re.match(r"^\d+\.\s", stripped):
            pdf.set_font("Helvetica", "", 11)
            pdf.set_text_color(50, 50, 50)
            pdf.cell(6)
            pdf.multi_cell(0, 6, stripped)
            pdf.ln(1)
        elif stripped.startswith("```"):
            pdf.set_font("Courier", "", 9)
            pdf.set_text_color(80, 80, 80)
            continue
        elif stripped.startswith("> "):
            pdf.set_font("Helvetica", "I", 11)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(8)
            pdf.multi_cell(0, 6, stripped[2:])
            pdf.ln(2)
        elif stripped.startswith("---") or stripped.startswith("***"):
            pdf.ln(2)
            pdf.set_draw_color(200, 200, 200)
            pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
            pdf.ln(4)
        else:
            # Normal paragraph — strip markdown bold/italic/links for clean text
            clean = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", stripped)  # [text](url) -> text
            clean = re.sub(r"\*\*(.+?)\*\*", r"\1", clean)  # **bold** -> bold
            clean = re.sub(r"\*(.+?)\*", r"\1", clean)  # *italic* -> italic
            clean = re.sub(r"`(.+?)`", r"\1", clean)  # `code` -> code
            pdf.set_font("Helvetica", "", 11)
            pdf.set_text_color(50, 50, 50)
            pdf.multi_cell(0, 6, clean)
            pdf.ln(1)

    # Footer
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 5, "Powered by lixSearch | search.elixpo.com", align="C")

    return pdf.output()


async def export_pdf():
    """POST /api/export/pdf — convert markdown response to downloadable PDF."""
    request_id = request.headers.get("X-Request-ID", str(uuid.uuid4())[:X_REQ_ID_SLICE_SIZE])

    try:
        data = await request.get_json()
        content = data.get("content", "").strip()
        title = data.get("title", "lixSearch Response").strip()

        if not content:
            return jsonify({"error": "content is required"}), 400

        pdf_bytes = _markdown_to_pdf(content, title)

        return Response(
            pdf_bytes,
            content_type="application/pdf",
            headers={
                "Content-Disposition": f'attachment; filename="lixsearch-{request_id}.pdf"',
                "X-Request-ID": request_id,
            },
        )

    except Exception as e:
        logger.error(f"[{request_id}] PDF export error: {e}", exc_info=True)
        return jsonify({"error": "PDF generation failed"}), 500
